# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
jdk:
- openjdk11

services:
- postgresql
before_install:
- psql -c 'create database cinema;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
env:
  global:
  - CODECOV_TOKEN="d7a5e3be-324e-4be9-9fba-78db0b51da42"
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту alexmur07@mail.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
    - alexmur008@gmail.com
    on_success: never # default: change
    on_failure: always # default: always